# Generated by Django 3.2.3 on 2021-05-26 09:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0011_auto_20210526_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='article_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='article_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
