# Generated by Django 3.2.3 on 2021-05-26 09:41

from django.db import migrations, models
# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0012_auto_20210526_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='article_content',
            field=models.TextField(),

            
            # field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='article_slug',
            field=models.SlugField(null=True),
        ),
    ]
