# Generated by Django 3.2.3 on 2021-05-26 11:09

import datetime
from django.db import migrations, models
import django.utils.timezone
# import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0014_auto_20210526_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_content',
            field=models.TextField(),
            # field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
