# Generated by Django 3.2.3 on 2021-05-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0015_auto_20210526_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='article_published',
        ),
        migrations.AlterField(
            model_name='department',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='picsZone'),
        ),
    ]
