# Generated by Django 3.2.3 on 2021-05-29 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0019_auto_20210529_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_slug',
        ),
        migrations.AlterField(
            model_name='member',
            name='about_me',
            field=models.TextField(default='', null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officer.member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
