# Generated by Django 3.2.3 on 2021-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0023_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
