# Generated by Django 3.2.3 on 2021-05-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0024_alter_member_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='article_published',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
    ]
