# Generated by Django 3.2.3 on 2021-05-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0025_auto_20210530_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
    ]
