# Generated by Django 3.2.3 on 2021-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0027_auto_20210530_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.TextField(max_length=15),
        ),
    ]
