# Generated by Django 3.2.3 on 2021-05-31 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0029_member_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 5, 9, 40, 270186)),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.ManyToManyField(to='officer.Member'),
        ),
    ]
