# Generated by Django 3.2.3 on 2021-05-31 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0030_auto_20210531_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
        migrations.AddField(
            model_name='profile',
            name='members',
            field=models.ManyToManyField(to='officer.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 9, 39, 5, 120435)),
        ),
    ]
