# Generated by Django 3.2.3 on 2021-05-31 13:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0032_auto_20210531_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, unique=True),
        ),
    ]
